name: Test

on: [ push ]

jobs:
  build:
      env:
        PIPENV_NO_INHERIT: 1
        PIPENV_IGNORE_VIRTUALENVS: 1

      runs-on: windows-latest

      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.10.8
            architecture: x64
        - name: Instalar dependências
          run: |
            python -m pip install --upgrade pip
            pip install pipenv
            pipenv sync --dev
            cp contrib/env-sample .env
        - name: Rodar flake8
          run: |
            pipenv run flake8 .
        - name: Rodar os Testes
          run: |
            pipenv run pytest --cov=pypro
        - name: Relatório Coverage
          env:
            CODECOV_TOKEN: '03525e52-3f9c-4cd9-97ac-ea5fdea1f317'
          run: |
            pipenv run codecov